import Head from "next/head";
import Main from "../components/Main";
import About from "../components/About";
import Skils from "../components/Skills";
import Portfolio from "../components/Portfolio";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alexander T. | Frontend Web Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main />
      <About />
      <Skils />
      <Portfolio />
      <Contact />
    </div>
  );
}
